### ISSUE TITLE
json2geobuf cannot handle extremely large JSON files

### ISSUE THREAD

**Issue by mattwigway** [mapbox/geobuf#66] opened 2016-07-13 21:42 UTC
When I try to pass an extremely large JSON file (438mb) through json2geobuf, I get the following error. It appears that this is because the file exceeds Node/V8's 256mb maximum size for a string.

```buffer.js:528
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:528:11)
    at Object.parse (native)
    at /Users/matthewc/conveyal/geobuf/bin/json2geobuf:12:24
    at ConcatStream.<anonymous> (/Users/matthewc/conveyal/geobuf/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (/Users/matthewc/conveyal/geobuf/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/Users/matthewc/conveyal/geobuf/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/Users/matthewc/conveyal/geobuf/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at ReadStream.onend (_stream_readable.js:517:10)
```

**Comment by mourner** [comment] 2016-08-15 11:27
It's a duplicate of https://github.com/mapbox/geobuf/issues/37 and requires a full redesign of the format to be streamable, and it's underway.

**Closed by mourner** 2016-08-15 11:27 UTC

**Comment by mattwigway** [comment] 2016-08-15 11:29
It's not necessarily a duplicate of #37. I have more than enough memory to
handle a file larger than 256mb without streaming writes.

**Comment by andrewharvey** [comment] 2016-08-15 11:33
> It's not necessarily a duplicate of #37. I have more than enough memory to
handle a file larger than 256mb without streaming writes.

Node has a fixed limit to the size of a string, regardless of how much memory your machine has (AFAIK), which the only workaround too is using node streaming read/writes.

**Comment by mourner** [comment] 2016-08-15 11:42
@mattwigway what's your Node version?
